### ISSUE TITLE
Issues with higher density data

### ISSUE THREAD

**Issue by Himaanshu09** [yalesong/hCRF-light#1]
When I ran this library with a dataset of 4200 files. Dimension of seqs data(93 columns and rows [not fixed]) It gave me accuracy to be somewhere around 0.0015 which is very low. I gave the split valid parameters to be same as split test. Can anyone explain the reason for this low accuracy?
Do I need to change seeds or any other parameter?

**Comment by yalesong** [comment]
From what you've described, it appears that you may want to transpose your data matrix. The number of rows corresponds to the feature dimension, and the number of columns represent the length of sequence. Each column should be a feature vector at time t.

If you share details of your dataset, I might help you better.

**Comment by Himaanshu09** [comment]
Hi Yale
I am using 'hcrf' model with following parameters:
'lgbfs' optimiser
nbHidden states= 4:4:12;
regFactorL2=10;
common.seed=02139;
verbose=false;
Yes I know I have taken the transpose of the data. Column refers to time samples(which vary from sample to sample) and rows refer to features.
I am sharing the mat file with you in order to give you a sense of the data. 
https://drive.google.com/file/d/0B1XHIsl5IHKdSjc1MTJFbzRsYlE/view?usp=sharing
Looking forward to your response. Kindly help me.

**Comment by Himaanshu09** [comment]
Hi Yale 
This is the sample file.I have 4200 such files. before passing into the library I am taking the tranpose and passing in the same format as ArmGesture dataset. Could you help me out ? Thanks!
[bad_amar_R_7.txt](https://github.com/yalesong/hCRF-light/files/128002/bad_amar_R_7.txt)

**Comment by yalesong** [comment]
Could you make sure your dataset is not the problem? I can hardly imagine an accuracy of 0.0015, as it means only about 6 samples were labelled correctly out of your 4200 samples. Have you tried the same dataset on other models, say linear SVM?

**Comment by Himaanshu09** [comment]
Hi Yale

yes I have tried my same model on HMM also where I am getting around 90%
accuracy. I even tried with small dataset(around 840 files)
and I got 31% accuracy.

--------------------
Himaanshu Gauba
ShARE Global Director Campus(Co-President)
Final Year
IIT Roorkee

Mobile: +91 8979530027
Social Media:LinkedIn <https://www.linkedin.com/in/himaanshu> | facebook
<https://www.facebook.com/himaanshu.gauba>

**Comment by yalesong** [comment]
Sorry for getting back on this late. Could you share with me the small dataset so I could help you debugging the issue?
