### ISSUE TITLE
windowsize

### ISSUE THREAD

**Issue by apoliver** [yalesong/hCRF-light#2]
Dear Yale,

Looks like this light version HCRF does not support window size for dependency range. Currently just consider consecutive nodes, right? Or is there a way to specify such window size in your current code? Thanks a lot.

**Comment by yalesong** [comment]
Yes, you are right. The current code doesn't support window size for dependency range. 

_In case you are interested: _
There are two ways to consider window size for dependency range: concatenation and temporal smoothing. The concatenation idea is proposed in Sy Bor Wang's CVPR'06 paper [1], where he concatenates neighboring observations into one vector; the input feature dimension increases W times with the window size W. An alternative is to perform Gaussian temporal smoothing over neighboring observations; the input feature dimension stays the same. 

I compared the performance of the two approaches and found that the latter outperforms the former both in terms of recognition accuracy and model complexity. (see Figure 2 in [2]).

I have implementation of the Gaussian temporal smoothing for the multi-view models (see: https://github.com/yalesong/hCRF-light/blob/master/libs/shared/hCRF/include/MultiviewFeatures.h#L24-L42). 

If there's enough interest, I will update the code for the non-multi-view cases too. Let me know.

[1] http://people.csail.mit.edu/sybor/cvpr06_wang.pdf
[2] http://people.csail.mit.edu/yalesong/publications/SongD2015IJCAI.pdf

**Comment by apoliver** [comment]
Thank you so much for the detailed clarification.

Yes, looks like Gaussian temporal smoothing is a good choice. It would be great if you can update non-multi-view case. :)

**Comment by apoliver** [comment]
Also, I am interested in obtaining the hidden states, instead of just the predicted class, but for the all classes (in particular the ground truth class), during testing. Looks like need I shall modify current c++ source code - the function Evaluator::computeLabels.

I am using vs 2008 also and can compile successfully. But came across some issues when running the matlab mex file. I guess maybe it's due to incorrect configuration in vs. Do you have any hints? Thanks.

**Comment by yalesong** [comment]
You can actually obtain the hidden states quite easily. For now it is implemented in this MATLAB wrapper : https://github.com/yalesong/hCRF-light/blob/master/apps/matHCRF/src/matHCRF.cpp#L707-L721

The posterior of hidden states can be accessed by passing the third return argument. Been a while since I used the functionality, but I believe you can do: 
``> [prob, label, hiddenstates] = matHCRF('getResults') ``
The third variable ``hiddenstates`` will contain the posteriors. 

What version of MATLAB are you using? It may be version issue (it's been more than 2 years since I updated this library... sorry.)

**Comment by apoliver** [comment]
Yes, the hidden states can be accessed.

Maybe my previous question was unclear. I mean, only the hidden states for the predicted class can be accessed, rather than the hidden states of all classes.

Or maybe in this code, different classes share the same hidden states space? so that no hidden states specific for each class?

**Comment by yalesong** [comment]
Sorry for misunderstanding! 

You are correct -- currently only the hidden states for the predicted class can be accessed. Different classes have different hidden state spaces; they don't share it. 

For HCRF, you could modify EvaluatorHCRF::computeSequenceLabel

**Comment by apoliver** [comment]
thank you so much Dr. Song. Finally I am able to modify the code and run successfully. :)

**Comment by apoliver** [comment]
BTW, it would be great if you can update the code with Gaussian temporal smoothing :)
