### ISSUE TITLE
Cannot find shared library

### ISSUE THREAD

**Issue by jbschiratti** [yalesong/hCRF-light#3]
I followed the instructions in `compile.sh` and got no error. 
After `make` and `make distribute`, I tried to run the command 
`./distribute/bin/hcrf-light` and got the following error : 
`./distribute/bin/hcrf-light: error while loading shared libraries: liblbfgs-1.8.so: cannot open shared object file: No such file or directory`
The library `liblbfgs-1.8.so` indeed exists in `./lib/liblbfgs/lib/.libs/`. How can I solve this problem ?

I am using Debian 8.7.

**Comment by yalesong** [comment]
Can you try adding to your LD_LIBRARY_PATH the directory path with liblbfgs-1.8.so?

**Comment by jbschiratti** [comment]
Thank you for your help. It solved the problem :+1:

**Comment by mohtamohit** [comment]
I'm getting a similar error and the suggested solution didn't work for me. Maybe I'm doing something wrong. Here is the screenshot of what I did. Would be grateful if you can help : 
![image](https://user-images.githubusercontent.com/16120547/36201097-da7d2aec-11a4-11e8-8b17-2b3eba679823.png)

**Comment by mohtamohit** [comment]
Fixed it myself. LD_LIBRARY_PATH should point to the directory containing path.so.something, not to path.so.something itself. :)
